# Generated by Django 4.1.1 on 2022-09-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='analista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creditos.analista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='EN PROCESO', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='urlDocumentos',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
