# Generated by Django 4.1.1 on 2022-09-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_solicitud_analista_solicitud_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='plazo_meses',
        ),
    ]
