# Generated by Django 4.1.1 on 2022-09-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_remove_solicitud_monto_remove_solicitud_plazo_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cliente',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creditos.cliente'),
            preserve_default=False,
        ),
    ]
