# Generated by Django 4.1.1 on 2022-09-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_remove_solicitud_cliente_solicitud_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('plazo_en_meses', models.IntegerField()),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditos.analista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditos.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
